#include "ice_melee.hpp"
#include "lunch_tin.hpp"
#include "steel_toe.hpp"
#include "glow_slag.hpp"
#include "tar_flask.hpp"
#include "mold_key.hpp"
#include "rail_switch_key.hpp"
#include "insulated_boots.hpp"
#include "steam_lance.hpp"
#include "machine_fittings.hpp"
#include "pocket_pump.hpp"
#include "hand_bellows.hpp"
#include "nail_board.hpp"
#include "chain_hook.hpp"
#include "bolt_pouch.hpp"
#include "emergency_foam.hpp"
#include "tension_spring.hpp"
#include "pocket_drill.hpp"
#include "coolant.hpp"
#include "barricade.hpp"
#include "magnet.hpp"
#include "arc_torch.hpp"
#include "foreman_whistle.hpp"
#include "quarry_charge.hpp"
#include "fuse_scissors.hpp"
#include "sled.hpp"
#include "snow_shelter.hpp"
#include "ice_anchor.hpp"
#include "effigy_mask.hpp"
#include "stillwater_bell.hpp"
#include "tuning_fork.hpp"
#include "folded_bridge.hpp"
#include "thaw_charge.hpp"
#include "heat_siphon.hpp"
#include "doorstop.hpp"
#include "borrowed_summer.hpp"
#include "harpoon.hpp"
#include "echo_pebble.hpp"
#include "circuits.hpp"
#include "storm_lantern.hpp"
#include "flare.hpp"
#include "catalog.hpp"
#include "ice_equipment.hpp"
#include "candles.hpp"
#include "coal.hpp"
#include "kettle.hpp"
#include "pressure.hpp"
#include "brine.hpp"
#include "alarms.hpp"
#include "fishing_line.hpp"
#include "fish.hpp"
#include "snow_globe.hpp"
#include "muffling.hpp"
#include "optics.hpp"
#include "eel_battery.hpp"
#include "snow_tools.hpp"
#include "quarry_tools.hpp"
#include "air_bladder.hpp"
#include "cold_flask.hpp"
#include "cold_remedies.hpp"
#include "heat_capsule.hpp"
#include "ice_footing.hpp"
#include "ice_projectiles.hpp"
#include "industrial_melee.hpp"
#include "rivet_gun.hpp"
#include "belt_tools.hpp"
#include "materials.hpp"
#include "woodland_tools.hpp"
#include "remedies.hpp"
#include "ground_tools.hpp"
#include "displacement.hpp"
#include "root_relics.hpp"
#include "woodland_traps.hpp"
#include "movement_tools.hpp"
#include "noisemakers.hpp"
#include "mixtures.hpp"
#include "shields.hpp"
#include "decoys.hpp"
#include "pocket_door.hpp"

#include <array>

namespace {
using Definition = const RegionalItem* (*)(ItemKind);
struct Entry { ItemKind kind; Definition definition; };

// One explicit owner per kind. Legacy definitions remain in inventory/item_pattern.
// Check order as well as count so enum additions cannot silently shift a lookup.
constexpr std::array<Entry, 156> entries{{
    {ItemKind::None, nullptr},
    {ItemKind::Wall, nullptr},
    {ItemKind::Medkit, nullptr},
    {ItemKind::Bandage, nullptr},
    {ItemKind::Bandaid, nullptr},
    {ItemKind::Fist, nullptr},
    {ItemKind::ConductorHat, nullptr},
    {ItemKind::Buckler, nullptr},
    {ItemKind::Pistol, nullptr},
    {ItemKind::Musket, nullptr},
    {ItemKind::Bow, nullptr},
    {ItemKind::RocketLauncher, nullptr},
    {ItemKind::Ammo, nullptr},
    {ItemKind::Bomb, nullptr},
    {ItemKind::SleepMeds, nullptr},
    {ItemKind::Stick, nullptr},
    {ItemKind::Shotgun, nullptr},
    {ItemKind::SMG, nullptr},
    {ItemKind::BearTrap, nullptr},
    {ItemKind::Mine, nullptr},
    {ItemKind::Pickaxe, nullptr},
    {ItemKind::RawMeat, nullptr},
    {ItemKind::CookedMeat, nullptr},
    {ItemKind::ThrowingRock, forest_item},
    {ItemKind::Hatchet, forest_item},
    {ItemKind::HuntingSpear, forest_item},
    {ItemKind::Crossbow, forest_item},
    {ItemKind::Blunderbuss, forest_item},
    {ItemKind::WoodenMaul, forest_item},
    {ItemKind::Rake, forest_item},
    {ItemKind::FlintKnife, forest_item},
    {ItemKind::Torch, forest_material_item},
    {ItemKind::Lighter, forest_material_item},
    {ItemKind::OilFlask, forest_material_item},
    {ItemKind::SapJar, forest_material_item},
    {ItemKind::WaterFlask, forest_material_item},
    {ItemKind::MushroomSpores, forest_material_item},
    {ItemKind::SmokePot, forest_material_item},
    {ItemKind::HoneyPot, forest_material_item},
    {ItemKind::Egg, forest_food_item},
    {ItemKind::FriedEgg, forest_food_item},
    {ItemKind::DiggingClaws, woodland_tool},
    {ItemKind::ResinGlue, woodland_tool},
    {ItemKind::SeedBag, woodland_tool},
    {ItemKind::LanternSeed, woodland_tool},
    {ItemKind::HerbBag, forest_remedy},
    {ItemKind::Splint, forest_remedy},
    {ItemKind::BitterRoot, forest_remedy},
    {ItemKind::Chili, forest_remedy},
    {ItemKind::FungalBread, forest_remedy},
    {ItemKind::BirdSeed, forest_ground_tool},
    {ItemKind::ThornCaltrops, forest_ground_tool},
    {ItemKind::HuntingHorn, forest_displacement_item},
    {ItemKind::RopeHook, forest_displacement_item},
    {ItemKind::RootDrill, forest_root_relic},
    {ItemKind::BlinkSeed, forest_root_relic},
    {ItemKind::Boomerang, forest_item},
    {ItemKind::RopeSnare, forest_trap_item},
    {ItemKind::SpringTrap, forest_trap_item},
    {ItemKind::AcornMine, forest_trap_item},
    {ItemKind::ThrowingNet, forest_movement_item},
    {ItemKind::StickyBoots, forest_movement_item},
    {ItemKind::RabbitCharm, forest_movement_item},
    {ItemKind::HandBell, forest_noisemaker},
    {ItemKind::Firecracker, forest_noisemaker},
    {ItemKind::StinkBomb, forest_mixture},
    {ItemKind::RottenFruit, forest_mixture},
    {ItemKind::PitchBomb, forest_mixture},
    {ItemKind::ShieldLantern, forest_shield},
    {ItemKind::ReflectingPan, forest_shield},
    {ItemKind::Scarecrow, forest_decoy},
    {ItemKind::StrawDecoy, forest_decoy},
    {ItemKind::WolfWhistle, forest_noisemaker},
    {ItemKind::ThunderAcorn, forest_root_relic},
    {ItemKind::PocketDoor, forest_pocket_door},
    {ItemKind::GritPouch, ice_footing_item},
    {ItemKind::IceNeedle, ice_projectile_item},
    {ItemKind::AirBladder, air_bladder_item},
    {ItemKind::ColdFlask, cold_flask_item},
    {ItemKind::HeatCapsule, heat_capsule_item},
    {ItemKind::WoolWrap, cold_remedy_item},
    {ItemKind::HotBroth, cold_remedy_item},
    {ItemKind::IcePoultice, cold_remedy_item},
    {ItemKind::Chisel, quarry_item},
    {ItemKind::IceBrick, quarry_item},
    {ItemKind::EelBattery, eel_battery_item},
    {ItemKind::SnowScoop, snow_tool_item},
    {ItemKind::Snowball, snow_tool_item},
    {ItemKind::LensCarbine, optics_item},
    {ItemKind::MirrorShard, optics_item},
    {ItemKind::CrystalLens, optics_item},
    {ItemKind::PrismBomb, optics_item},
    {ItemKind::BlackFelt, optics_item},
    {ItemKind::MufflingFelt, muffling_item},
    {ItemKind::AlarmClock, alarm_item},
    {ItemKind::FishingLine, fishing_line_item},
    {ItemKind::SmokedFish, fish_item},
    {ItemKind::SnowGlobe, snow_globe_item},
    {ItemKind::SaltedKelp, fish_item},
    {ItemKind::BrineFlask, brine_item},
    {ItemKind::CandleStub, candle_supply},
    {ItemKind::WickSpool, candle_supply},
    {ItemKind::CoalLump, coal_item},
    {ItemKind::SteamKettle, kettle_item},
    {ItemKind::PressureValve, pressure_item},
    {ItemKind::Sealant, pressure_item},
    {ItemKind::SkateBlade, ice_equipment_item},
    {ItemKind::Crampons, ice_equipment_item},
    {ItemKind::SignalFlare, flare_item},
    {ItemKind::CopperWire, circuit_item},
    {ItemKind::GroundingSpike, circuit_item},
    {ItemKind::StormLantern, storm_lantern_item},
    {ItemKind::EchoPebble, echo_pebble_item},
    {ItemKind::HarpoonGun, harpoon_item},
    {ItemKind::EmergencyDoorstop, doorstop_item},
    {ItemKind::BorrowedSummer, borrowed_summer_item},
    {ItemKind::HeatSiphon, heat_siphon_item},
    {ItemKind::ThawCharge, thaw_charge_item},
    {ItemKind::FoldedBridge, folded_bridge_item},
    {ItemKind::TuningFork, tuning_fork_item},
    {ItemKind::StillwaterBell, stillwater_bell_item},
    {ItemKind::EffigyMask, effigy_mask_item},
    {ItemKind::IceAnchor, ice_anchor_item},
    {ItemKind::SnowShelter, snow_shelter_item},
    {ItemKind::Sled, sled_item},
    {ItemKind::ForemanWhistle, foreman_whistle_item},
    {ItemKind::QuarryCharge, quarry_charge_item},
    {ItemKind::FuseScissors, fuse_scissors_item},
    {ItemKind::PressHammer, industrial_melee_item},
    {ItemKind::RubberMallet, industrial_melee_item},
    {ItemKind::RivetGun, rivet_gun_item},
    {ItemKind::BeltCrank, belt_tool_item},
    {ItemKind::BrakeShoe, belt_tool_item},
    {ItemKind::ArcTorch, arc_torch_item},
    {ItemKind::HorseshoeMagnet, magnet_item},
    {ItemKind::FoldingBarricade, barricade_item},
    {ItemKind::CoolantCan, coolant_item},
    {ItemKind::PocketDrill, pocket_drill_item},
    {ItemKind::TensionSpring, tension_spring_item},
    {ItemKind::EmergencyFoam, emergency_foam_item},
    {ItemKind::BoltPouch, bolt_pouch_item},
    {ItemKind::ChainHook, chain_hook_item},
    {ItemKind::NailBoard, nail_board_item},
    {ItemKind::HandBellows, hand_bellows_item},
    {ItemKind::PocketPump, pocket_pump_item},
    {ItemKind::NozzleElbow, nozzle_elbow_item},
    {ItemKind::MoldKey, mold_key_item},
    {ItemKind::SteamLance, steam_lance_item},
    {ItemKind::TarFlask, tar_flask_item},
    {ItemKind::RailSwitchKey, rail_switch_key_item},
    {ItemKind::InsulatedBoots, insulated_boots_item},
    {ItemKind::GlowSlag, glow_slag_item},
    {ItemKind::SteelToeCap, steel_toe_item},
    {ItemKind::LunchTin, lunch_tin_item},
    {ItemKind::IceAxe, ice_melee_item},
    {ItemKind::TuskPike, ice_melee_item},
}};
constexpr bool valid_entries() {
    if (entries.size() != static_cast<std::size_t>(ItemKind::Count)) return false;
    for (std::size_t i=0; i<entries.size(); ++i)
        if (static_cast<std::size_t>(entries[i].kind) != i) return false;
    return true;
}
static_assert(valid_entries());
} // namespace

const RegionalItem* regional_item(ItemKind kind) {
    const auto index=static_cast<std::size_t>(kind);
    if (index>=entries.size()) return nullptr;
    const Definition definition=entries[index].definition;
    return definition ? definition(kind) : nullptr;
}
