#include "supply.hpp"

#include <array>

namespace {
constexpr unsigned R=1U<<static_cast<unsigned>(LootSource::Reward);
constexpr unsigned S=1U<<static_cast<unsigned>(LootSource::Shop);
constexpr unsigned W=1U<<static_cast<unsigned>(LootSource::Weapon);
constexpr unsigned C=1U<<static_cast<unsigned>(LootSource::Cache);
constexpr unsigned T=1U<<static_cast<unsigned>(LootSource::Secret);
constexpr unsigned M=1U<<static_cast<unsigned>(LootSource::Workshop);

// MEMBERSHIP: One row per kind. Sources select these entries; bespoke room/animal
// supplies still specify their actual contents. Weight/stage are native availability.
// Role is the primary practical use, not every possible interaction. Portable
// combat/survival/mobility counts separately from matching-scene tools and toys.
constexpr std::array<ItemSupply, static_cast<std::size_t>(ItemKind::Count)> entries{{
    {ItemKind::None, ItemOrigin::Shared, 0, 1, 1, 0, ItemRole::None},
    {ItemKind::Wall, ItemOrigin::Shared, 0, 1, 1, 0, ItemRole::None},
    {ItemKind::Medkit, ItemOrigin::Shared, 3, 1, 1, R|S|C|T, ItemRole::Survival},
    {ItemKind::Bandage, ItemOrigin::Shared, 8, 1, 3, R|S|C|T, ItemRole::Survival},
    {ItemKind::Bandaid, ItemOrigin::Shared, 8, 1, 5, R|S|C|T, ItemRole::Oddity},
    {ItemKind::Fist, ItemOrigin::Shared, 0, 1, 1, 0, ItemRole::None},
    {ItemKind::ConductorHat, ItemOrigin::Industrial, 1, 3, 1, R|S|C|T, ItemRole::Combat},
    {ItemKind::Buckler, ItemOrigin::Shared, 3, 1, 1, R|S|C|T, ItemRole::Combat},
    {ItemKind::Pistol, ItemOrigin::Industrial, 8, 1, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::Musket, ItemOrigin::Industrial, 3, 2, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::Bow, ItemOrigin::Forest, 8, 1, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::RocketLauncher, ItemOrigin::Industrial, 1, 3, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::Ammo, ItemOrigin::Shared, 8, 1, 2, R|S|C|T, ItemRole::Utility},
    {ItemKind::Bomb, ItemOrigin::Shared, 3, 1, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::SleepMeds, ItemOrigin::Shared, 3, 1, 3, R|S|C|T, ItemRole::Combat},
    {ItemKind::Stick, ItemOrigin::Forest, 8, 1, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::Shotgun, ItemOrigin::Industrial, 3, 2, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::SMG, ItemOrigin::Industrial, 1, 3, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::BearTrap, ItemOrigin::Forest, 3, 1, 2, R|S|C|T|M, ItemRole::Combat},
    {ItemKind::Mine, ItemOrigin::Industrial, 3, 1, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::Pickaxe, ItemOrigin::Shared, 8, 1, 1, R|S|C|T|W|M, ItemRole::Mobility},
    {ItemKind::RawMeat, ItemOrigin::Shared, 8, 1, 2, R|S|C|T, ItemRole::Utility},
    {ItemKind::CookedMeat, ItemOrigin::Shared, 8, 1, 2, R|S|C|T, ItemRole::Survival},
    {ItemKind::ThrowingRock, ItemOrigin::Forest, 8, 1, 6, R|S|C|T, ItemRole::Combat},
    {ItemKind::Hatchet, ItemOrigin::Forest, 8, 1, 1, R|S|C|T|W|M, ItemRole::Combat},
    {ItemKind::HuntingSpear, ItemOrigin::Forest, 3, 1, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::Crossbow, ItemOrigin::Forest, 3, 2, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::Blunderbuss, ItemOrigin::Forest, 3, 3, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::WoodenMaul, ItemOrigin::Forest, 3, 1, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::Rake, ItemOrigin::Forest, 8, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::FlintKnife, ItemOrigin::Forest, 8, 1, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::Torch, ItemOrigin::Forest, 8, 1, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::Lighter, ItemOrigin::Forest, 8, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::OilFlask, ItemOrigin::Forest, 8, 1, 2, R|S|C|T, ItemRole::Utility},
    {ItemKind::SapJar, ItemOrigin::Forest, 8, 1, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::WaterFlask, ItemOrigin::Forest, 8, 1, 2, R|S|C|T|M, ItemRole::Survival},
    {ItemKind::MushroomSpores, ItemOrigin::Forest, 8, 1, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::SmokePot, ItemOrigin::Forest, 3, 1, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::HoneyPot, ItemOrigin::Forest, 3, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::Egg, ItemOrigin::Forest, 8, 1, 3, R|S|C|T, ItemRole::Utility},
    {ItemKind::FriedEgg, ItemOrigin::Forest, 8, 1, 2, R|S|C|T, ItemRole::Survival},
    {ItemKind::DiggingClaws, ItemOrigin::Forest, 3, 1, 1, R|S|C|T|W|M, ItemRole::Combat},
    {ItemKind::ResinGlue, ItemOrigin::Forest, 8, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::SeedBag, ItemOrigin::Forest, 8, 1, 1, R|S|C|T, ItemRole::Combat},
    {ItemKind::LanternSeed, ItemOrigin::Forest, 8, 1, 1, R|S|C|T, ItemRole::Oddity},
    {ItemKind::HerbBag, ItemOrigin::Forest, 3, 1, 1, R|S|C|T, ItemRole::Survival},
    {ItemKind::Splint, ItemOrigin::Forest, 3, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::BitterRoot, ItemOrigin::Forest, 8, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::Chili, ItemOrigin::Forest, 8, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::FungalBread, ItemOrigin::Forest, 3, 1, 1, R|S|C|T, ItemRole::Survival},
    {ItemKind::BirdSeed, ItemOrigin::Forest, 8, 1, 3, R|S|C|T, ItemRole::Utility},
    {ItemKind::ThornCaltrops, ItemOrigin::Forest, 3, 1, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::HuntingHorn, ItemOrigin::Forest, 3, 1, 1, R|S|C|T, ItemRole::Combat},
    {ItemKind::RopeHook, ItemOrigin::Forest, 3, 1, 1, R|S|C|T|M, ItemRole::Mobility},
    {ItemKind::RootDrill, ItemOrigin::Forest, 1, 3, 1, R|S|C|T, ItemRole::Mobility},
    {ItemKind::BlinkSeed, ItemOrigin::Forest, 1, 3, 2, R|S|C|T, ItemRole::Mobility},
    {ItemKind::Boomerang, ItemOrigin::Forest, 3, 1, 1, R|S|C|T, ItemRole::Combat},
    {ItemKind::RopeSnare, ItemOrigin::Forest, 3, 1, 2, R|S|C|T|M, ItemRole::Combat},
    {ItemKind::SpringTrap, ItemOrigin::Forest, 3, 2, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::AcornMine, ItemOrigin::Forest, 3, 2, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::ThrowingNet, ItemOrigin::Forest, 3, 2, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::StickyBoots, ItemOrigin::Forest, 3, 1, 1, R|S|C|T, ItemRole::Survival},
    {ItemKind::RabbitCharm, ItemOrigin::Forest, 1, 3, 1, R|S|C|T, ItemRole::Mobility},
    {ItemKind::HandBell, ItemOrigin::Forest, 8, 1, 1, R|S|C|T, ItemRole::Oddity},
    {ItemKind::Firecracker, ItemOrigin::Forest, 3, 1, 3, R|S|C|T, ItemRole::Utility},
    {ItemKind::StinkBomb, ItemOrigin::Forest, 3, 1, 2, R|S|C|T, ItemRole::Oddity},
    {ItemKind::RottenFruit, ItemOrigin::Forest, 8, 1, 3, R|S|C|T, ItemRole::Oddity},
    {ItemKind::PitchBomb, ItemOrigin::Forest, 3, 1, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::ShieldLantern, ItemOrigin::Forest, 3, 1, 1, R|S|C|T, ItemRole::Combat},
    {ItemKind::ReflectingPan, ItemOrigin::Forest, 3, 1, 1, R|S|C|T, ItemRole::Combat},
    {ItemKind::Scarecrow, ItemOrigin::Forest, 3, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::StrawDecoy, ItemOrigin::Forest, 3, 1, 1, R|S|C|T, ItemRole::Combat},
    {ItemKind::WolfWhistle, ItemOrigin::Forest, 3, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::ThunderAcorn, ItemOrigin::Forest, 1, 3, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::PocketDoor, ItemOrigin::Forest, 1, 3, 1, R|S|C|T, ItemRole::Mobility},
    {ItemKind::GritPouch, ItemOrigin::Ice, 8, 1, 1, R|S|C|T, ItemRole::Mobility},
    {ItemKind::IceNeedle, ItemOrigin::Ice, 8, 1, 3, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::AirBladder, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::ColdFlask, ItemOrigin::Ice, 8, 1, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::HeatCapsule, ItemOrigin::Ice, 3, 1, 2, R|S|C|T, ItemRole::Survival},
    {ItemKind::WoolWrap, ItemOrigin::Ice, 8, 1, 1, R|S|C|T, ItemRole::Survival},
    {ItemKind::HotBroth, ItemOrigin::Ice, 8, 1, 2, R|S|C|T, ItemRole::Survival},
    {ItemKind::IcePoultice, ItemOrigin::Ice, 3, 1, 2, R|S|C|T, ItemRole::Survival},
    {ItemKind::Chisel, ItemOrigin::Ice, 8, 1, 1, R|S|C|T|W|M, ItemRole::Combat},
    {ItemKind::IceBrick, ItemOrigin::Ice, 8, 1, 2, R|S|C|T|M, ItemRole::Combat},
    {ItemKind::EelBattery, ItemOrigin::Ice, 3, 2, 1, R|S|C|T, ItemRole::Combat},
    {ItemKind::SnowScoop, ItemOrigin::Ice, 3, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::Snowball, ItemOrigin::Ice, 8, 1, 3, R|S|C|T, ItemRole::Utility},
    {ItemKind::LensCarbine, ItemOrigin::Ice, 1, 3, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::MirrorShard, ItemOrigin::Ice, 3, 2, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::CrystalLens, ItemOrigin::Ice, 3, 2, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::PrismBomb, ItemOrigin::Ice, 1, 3, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::BlackFelt, ItemOrigin::Ice, 3, 1, 2, R|S|C|T, ItemRole::Utility},
    {ItemKind::MufflingFelt, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::AlarmClock, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Oddity},
    {ItemKind::FishingLine, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::SmokedFish, ItemOrigin::Ice, 8, 1, 2, R|S|C|T, ItemRole::Survival},
    {ItemKind::SnowGlobe, ItemOrigin::Ice, 1, 3, 1, R|S|C|T, ItemRole::Combat},
    {ItemKind::SaltedKelp, ItemOrigin::Ice, 8, 1, 2, R|S|C|T, ItemRole::Utility},
    {ItemKind::BrineFlask, ItemOrigin::Ice, 8, 1, 2, R|S|C|T, ItemRole::Utility},
    {ItemKind::CandleStub, ItemOrigin::Ice, 8, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::WickSpool, ItemOrigin::Ice, 8, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::CoalLump, ItemOrigin::Ice, 8, 1, 3, R|S|C|T, ItemRole::Utility},
    {ItemKind::SteamKettle, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::PressureValve, ItemOrigin::Ice, 3, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::Sealant, ItemOrigin::Ice, 3, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::SkateBlade, ItemOrigin::Ice, 3, 1, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::Crampons, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Mobility},
    {ItemKind::SignalFlare, ItemOrigin::Ice, 3, 1, 2, R|S|C|T, ItemRole::Combat},
    {ItemKind::CopperWire, ItemOrigin::Ice, 3, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::GroundingSpike, ItemOrigin::Ice, 3, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::StormLantern, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::EchoPebble, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Oddity},
    {ItemKind::HarpoonGun, ItemOrigin::Ice, 1, 3, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::EmergencyDoorstop, ItemOrigin::Ice, 3, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::BorrowedSummer, ItemOrigin::Ice, 1, 3, 1, R|S|C|T, ItemRole::Survival},
    {ItemKind::HeatSiphon, ItemOrigin::Ice, 1, 3, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::ThawCharge, ItemOrigin::Ice, 3, 1, 2, R|S|C|T, ItemRole::Mobility},
    {ItemKind::FoldedBridge, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Mobility},
    {ItemKind::TuningFork, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::StillwaterBell, ItemOrigin::Ice, 1, 3, 1, R|S|C|T, ItemRole::Mobility},
    {ItemKind::EffigyMask, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Utility},
    {ItemKind::IceAnchor, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Mobility},
    {ItemKind::SnowShelter, ItemOrigin::Ice, 3, 1, 1, R|S|C|T, ItemRole::Combat},
    {ItemKind::Sled, ItemOrigin::Ice, 1, 3, 1, R|S|C|T, ItemRole::Mobility},
    {ItemKind::ForemanWhistle, ItemOrigin::Industrial, 1, 3, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::QuarryCharge, ItemOrigin::Industrial, 3, 1, 2, R|S|C|T, ItemRole::Mobility},
    {ItemKind::FuseScissors, ItemOrigin::Industrial, 8, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::PressHammer, ItemOrigin::Industrial, 1, 3, 1, R|S|C|T|W|M, ItemRole::Combat},
    {ItemKind::RubberMallet, ItemOrigin::Industrial, 8, 1, 1, R|S|C|T|W|M, ItemRole::Combat},
    {ItemKind::RivetGun, ItemOrigin::Industrial, 1, 3, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::BeltCrank, ItemOrigin::Industrial, 3, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::BrakeShoe, ItemOrigin::Industrial, 8, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::ArcTorch, ItemOrigin::Industrial, 3, 2, 1, R|S|C|T|W|M, ItemRole::Combat},
    {ItemKind::HorseshoeMagnet, ItemOrigin::Industrial, 3, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::FoldingBarricade, ItemOrigin::Industrial, 3, 2, 1, R|S|C|T|M, ItemRole::Combat},
    {ItemKind::CoolantCan, ItemOrigin::Industrial, 6, 1, 1, R|S|C|T|M, ItemRole::Survival},
    {ItemKind::PocketDrill, ItemOrigin::Industrial, 3, 2, 1, R|S|C|T|W|M, ItemRole::Mobility},
    {ItemKind::TensionSpring, ItemOrigin::Industrial, 3, 1, 3, R|S|C|T|M, ItemRole::Mobility},
    {ItemKind::EmergencyFoam, ItemOrigin::Industrial, 3, 1, 2, R|S|C|T|M, ItemRole::Survival},
    {ItemKind::BoltPouch, ItemOrigin::Industrial, 8, 1, 3, R|S|C|T|M, ItemRole::Combat},
    {ItemKind::ChainHook, ItemOrigin::Industrial, 3, 1, 1, R|S|C|T|M, ItemRole::Mobility},
    {ItemKind::NailBoard, ItemOrigin::Industrial, 7, 1, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::HandBellows, ItemOrigin::Industrial, 5, 1, 1, R|S|C|T|M, ItemRole::Combat},
    {ItemKind::PocketPump, ItemOrigin::Industrial, 3, 1, 1, R|S|C|T|M, ItemRole::Survival},
    {ItemKind::NozzleElbow, ItemOrigin::Industrial, 3, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::MoldKey, ItemOrigin::Industrial, 3, 1, 1, R|S|C|T|M, ItemRole::Utility},
    {ItemKind::SteamLance, ItemOrigin::Industrial, 5, 1, 1, W|R|S|C|T|M, ItemRole::Utility},
    {ItemKind::TarFlask, ItemOrigin::Industrial, 4, 1, 3, R|S|C|T|M, ItemRole::Combat},
    {ItemKind::RailSwitchKey, ItemOrigin::Industrial, 0, 1, 1, 0, ItemRole::Utility},
    {ItemKind::InsulatedBoots, ItemOrigin::Industrial, 3, 1, 1, R|S|C|T|M, ItemRole::Survival},
    {ItemKind::GlowSlag, ItemOrigin::Industrial, 3, 1, 1, R|S|C|T|M, ItemRole::Oddity},
    {ItemKind::SteelToeCap, ItemOrigin::Industrial, 4, 1, 1, R|S|C|T|M, ItemRole::Combat},
    {ItemKind::LunchTin, ItemOrigin::Industrial, 5, 1, 1, R|S|C|T|M, ItemRole::Survival},
    {ItemKind::IceAxe, ItemOrigin::Ice, 8, 1, 1, R|S|C|T|W|M, ItemRole::Combat},
    {ItemKind::TuskPike, ItemOrigin::Ice, 6, 2, 1, R|S|C|T|W, ItemRole::Combat},
    {ItemKind::RiverFish, ItemOrigin::Forest, 0, 1, 2, 0, ItemRole::Survival},
    {ItemKind::Slap, ItemOrigin::Shared, 0, 1, 1, 0, ItemRole::None},
    {ItemKind::ParryPan, ItemOrigin::Shared, 0, 1, 1, 0, ItemRole::None},
    {ItemKind::Jump, ItemOrigin::Shared, 0, 1, 1, 0, ItemRole::None},
    {ItemKind::Grapple, ItemOrigin::Shared, 0, 1, 1, 0, ItemRole::None},
    {ItemKind::Shove, ItemOrigin::Shared, 0, 1, 1, 0, ItemRole::None},
    {ItemKind::Kick, ItemOrigin::Shared, 0, 1, 1, 0, ItemRole::None},
    {ItemKind::Elbow, ItemOrigin::Shared, 0, 1, 1, 0, ItemRole::None},
    {ItemKind::GodFist, ItemOrigin::Shared, 0, 1, 1, 0, ItemRole::None},
    {ItemKind::Balloon, ItemOrigin::Shared, 3, 1, 1, S|C|T, ItemRole::Mobility},
    {ItemKind::CrushShield, ItemOrigin::Industrial, 3, 2, 1, S|W|C|T, ItemRole::Combat},
}};
constexpr bool valid_entries() {
    if (entries.size()!=static_cast<std::size_t>(ItemKind::Count)) return false;
    for (std::size_t i=0;i<entries.size();++i)
        if (static_cast<std::size_t>(entries[i].kind)!=i ||
            (entries[i].sources && entries[i].role==ItemRole::None)) return false;
    return true;
}
static_assert(valid_entries(), "Register each item once in enum order, including explicit non-loot entries");
} // namespace

const ItemSupply& item_supply(ItemKind kind) {
    const auto index=static_cast<std::size_t>(kind);
    return entries[index<entries.size() ? index : 0];
}
