#!/usr/bin/env python3
"""Rebuild checked-in Vulkan shader binaries; ordinary builds need no compiler."""
from pathlib import Path
import struct, subprocess, tempfile
root=Path(__file__).resolve().parents[1]
output=['// Generated by tools/compile_renderer_shaders.py. Do not edit.','#pragma once','#include <cstdint>','namespace tr::vk {']
with tempfile.TemporaryDirectory() as temp:
    for stage in ['vert','frag']:
        binary=Path(temp)/stage
        subprocess.run(['glslangValidator','-V',str(root/'shaders/renderer'/('sprite.'+stage)),'-o',str(binary)],check=True)
        blob=binary.read_bytes();words=struct.unpack('<'+'I'*(len(blob)//4),blob)
        output.append('inline constexpr std::uint32_t sprite_'+stage+'[]{')
        output += [','.join(hex(w) for w in words[i:i+8])+',' for i in range(0,len(words),8)]
        output.append('};')
output.append('}')
(root/'src/renderer/shaders_spirv.hpp').write_text('\n'.join(output)+'\n')
