#pragma once

#include <cstddef>
#include <array>
#include <string_view>

enum class SoundId : std::size_t {
    ApeScream, BallBounce1, BallBounce2, BallBounce3, BallBounce4,
    BallDrop, BallHitPaddle, BallHitPaddleEr, BallWallBounce,
    Confirm, Death, Explosion, Explosion1, Explosion2, Explosion3,
    AnimalCrush1, AnimalCrush2, HitBlock1, LevelLoss, LevelStart,
    LevelWin, SmallLaser, SturdyBlockBouncedOn, SuperConfirm,
    Step1, Step2, BoxBreak, BlockLand, ZombieGrowl1, ZombieGrowl2,
    ZombieScratch1, Punch1, ClothRip, CantUse, Chick, Hen, Rooster,
    DistantTrainSound, RailPlace, TrainPassing, Drop,
    FirePanic, FireTrample, FireOut,
    LeavesCrunch, TwigSnap, PlantCut, SporePuff, WoodCrack, PotBreak,
    ZombieTopple, EncounterBell, GateClose, GraveRise, EncounterClear, CoinPickup,
    BoarSnort, BoarHit, ShellKnock, ShellScrape, ToadCroak, ToadPuff, MothFlutter, MothDust, MimicWake, MimicBite, WolfHowl, WolfBite, BearRear, BearSlam, BatSqueak, BatBite,
    RockThrow, RockImpact, AxeSwing, SpearThrust, CrossbowShot, BlunderShot, MaulSwing, RakeSweep, KnifeStab, WeaponReload, WeaponEmpty,
    BumpWood, BumpStone,
    CookingSizzle, WaterStep1, WaterStep2, WaterDouse, MeatMunch, ChickenPeck, BowDraw, BowRelease, ArrowImpact, BombThrow, BombLand, BombFuse, FistWindup, StickWindup, PickaxeWindup, FireCatch, TorchSwing, LighterSpark, BottleThrow, BottleBreak, WaterPour, HoneyPlace,
    PistolShot, MusketShot, ShotgunShot, SmgShot, RocketLaunch,
    PistolReload, ShellReload, PowderReload, CrossbowReload, RocketReload, EggEat, RootCoil, RootLash, BrambleRustle, BrambleStrike,
    MosquitoBuzz, MosquitoBite, OwlHoot, OwlSwoop, OwlClaw, WoodpeckerRattle, WoodpeckerDrill, BeakStuck,
    NestBuzz, WaspRelease, WaspWarning, WaspSting, NestBreak,
    GoblinHiss, GoblinChuckle, ScavengeTake, CrowCall, CrowRattle, CrowSnatch,
    WormWarning, WormBite, WormBurrow, WormSplit,
    ClawScratch, ResinRepair, SeedPlant, CoverGrow, LanternPlant,
    HerbsChew, SplintBind, RootChew, ChiliBite, BreadMunch,
    SeedScatter, SeedPeck, ThornScatter, ThornPrick,
    HornBlast, HookCast, HookLatch, HookReel, HookRelease,
    DrillStart, DrillBite, DrillStop, SwapCast, SwapFold, SwapFade,
    BoomerangThrow, BoomerangHit, BoomerangCatch, BoomerangLand,
    NetThrow, NetCatch, NetFall, BootsStick, BootsRelease, RabbitEscape, OilSlip,
    StinkThrow, StinkBreak, FruitThrow, FruitSplat, FruitMunch, PitchThrow, PitchFuse, PitchLand, PitchBurst, ScentSniff, NauseaGag,
    HandBell, CrackerThrow, CrackerFuse, CrackerLand, CrackerBang,
    SnarePlace, SnareCatch, SnareRelease, SpringSet, SpringLaunch, SpringBreak, AcornSet, AcornBurst,
    LanternRaise, LanternBlock, LanternBreak, PanRaise, PanReflect, PanBreak, ScarecrowPlant, ScarecrowTear, DecoyPlant, DecoyHit, DecoyTear, WolfWhistle, WolfAnswer, ThunderThrow, ThunderCrack, PocketPlace, PocketLink, PocketTravel, PocketBlocked,
    SnowStep1, SnowStep2, IceStep1, IceStep2,
    SkaterPush, SkaterBrake, SkaterHit, SkaterBreak, GritScatter, GritEmpty, IceSlip,
    FrostInhale, FrostExhale, FrostFlutter, FrostDeath, FrostPuffHit, IceMelt, IceNeedleThrow, IceNeedleHit,
    DiverBubbles, DiverRing, DiverRise, DiverWindup, DiverStrike, DiverDive, DiverDeath,
    Count,
};

inline constexpr std::array<std::string_view, static_cast<std::size_t>(SoundId::Count)> sound_names{
    "ape_scream", "ball_bounce1", "ball_bounce2", "ball_bounce3", "ball_bounce4",
    "ball_drop", "ball_hit_paddle", "ball_hit_paddle_er", "ball_wall_bounce",
    "confirm", "death", "explosion", "explosion1", "explosion2", "explosion3",
    "animal_crush1", "animal_crush2", "hit_block1", "level_loss", "level_start",
    "level_win", "small_laser", "sturdy_block_bounced_on", "super_confirm",
    "step1", "step2", "box_break", "block_land", "zombie_growl1", "zombie_growl2",
    "zombie_scratch1", "punch1", "cloth_rip", "cant_use", "chick", "hen", "rooster",
    "distant_train_sound", "rail_place", "train_passing", "drop", "fire_panic", "fire_trample", "fire_out",
    "leaves_crunch", "twig_snap", "plant_cut", "spore_puff", "wood_crack", "pot_break",
    "zombie_topple", "encounter_bell", "gate_close", "grave_rise", "encounter_clear", "coin_pickup",
    "boar_snort", "boar_hit", "shell_knock", "shell_scrape", "toad_croak", "toad_puff", "moth_flutter", "moth_dust", "mimic_wake", "mimic_bite", "wolf_howl", "wolf_bite", "bear_rear", "bear_slam", "bat_squeak", "bat_bite",
    "rock_throw", "rock_impact", "axe_swing", "spear_thrust", "crossbow_shot", "blunder_shot", "maul_swing", "rake_sweep", "knife_stab", "weapon_reload", "weapon_empty",
    "bump_wood", "bump_stone", "cooking_sizzle", "water_step1", "water_step2", "water_douse", "meat_munch", "chicken_peck", "bow_draw", "bow_release", "arrow_impact", "bomb_throw", "bomb_land", "bomb_fuse", "fist_windup", "stick_windup", "pickaxe_windup", "fire_catch", "torch_swing", "lighter_spark", "bottle_throw", "bottle_break", "water_pour", "honey_place",
    "pistol_shot", "musket_shot", "shotgun_shot", "smg_shot", "rocket_launch",
    "pistol_reload", "shell_reload", "powder_reload", "crossbow_reload", "rocket_reload", "egg_eat", "root_coil", "root_lash", "bramble_rustle", "bramble_strike",
    "mosquito_buzz", "mosquito_bite", "owl_hoot", "owl_swoop", "owl_claw", "woodpecker_rattle", "woodpecker_drill", "beak_stuck",
    "nest_buzz", "wasp_release", "wasp_warning", "wasp_sting", "nest_break",
    "goblin_hiss", "goblin_chuckle", "scavenge_take", "crow_call", "crow_rattle", "crow_snatch",
    "worm_warning", "worm_bite", "worm_burrow", "worm_split",
    "claw_scratch", "resin_repair", "seed_plant", "cover_grow", "lantern_plant",
    "herbs_chew", "splint_bind", "root_chew", "chili_bite", "bread_munch",
    "seed_scatter", "seed_peck", "thorn_scatter", "thorn_prick",
    "horn_blast", "hook_cast", "hook_latch", "hook_reel", "hook_release",
    "drill_start", "drill_bite", "drill_stop", "swap_cast", "swap_fold", "swap_fade",
    "boomerang_throw", "boomerang_hit", "boomerang_catch", "boomerang_land",
    "net_throw", "net_catch", "net_fall", "boots_stick", "boots_release", "rabbit_escape", "oil_slip",
    "stink_throw", "stink_break", "fruit_throw", "fruit_splat", "fruit_munch", "pitch_throw", "pitch_fuse", "pitch_land", "pitch_burst", "scent_sniff", "nausea_gag",
    "hand_bell", "cracker_throw", "cracker_fuse", "cracker_land", "cracker_bang",
    "snare_place", "snare_catch", "snare_release", "spring_set", "spring_launch", "spring_break", "acorn_set", "acorn_burst",
    "lantern_raise", "lantern_block", "lantern_break", "pan_raise", "pan_reflect", "pan_break", "scarecrow_plant", "scarecrow_tear", "decoy_plant", "decoy_hit", "decoy_tear", "wolf_whistle", "wolf_answer", "thunder_throw", "thunder_crack", "pocket_place", "pocket_link", "pocket_travel", "pocket_blocked",
    "snow_step1", "snow_step2", "ice_step1", "ice_step2",
    "skater_push", "skater_brake", "skater_hit", "skater_break", "grit_scatter", "grit_empty", "ice_slip",
    "frost_inhale", "frost_exhale", "frost_flutter", "frost_death", "frost_puff_hit", "ice_melt", "ice_needle_throw", "ice_needle_hit",
    "diver_bubbles", "diver_ring", "diver_rise", "diver_windup", "diver_strike", "diver_dive", "diver_death",
};
