add_library(teeming_renderer STATIC
    src/renderer/device.cpp src/renderer/draw.cpp src/renderer/text.cpp src/renderer/atlas.cpp)
target_link_libraries(teeming_renderer PUBLIC SDL3::SDL3 SDL3_image::SDL3_image)
target_include_directories(teeming_renderer PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/src")
if(EMSCRIPTEN)
    target_sources(teeming_renderer PRIVATE src/renderer/webgl.cpp src/renderer/webgpu.cpp)
    target_link_options(teeming_renderer INTERFACE "SHELL:--pre-js ${CMAKE_CURRENT_SOURCE_DIR}/src/renderer/webgpu_runtime.js")
else()
    find_package(Vulkan REQUIRED)
    target_sources(teeming_renderer PRIVATE src/renderer/vulkan_context.cpp
        src/renderer/vulkan_resources.cpp src/renderer/vulkan_pipeline.cpp src/renderer/vulkan_draw.cpp)
    target_link_libraries(teeming_renderer PUBLIC Vulkan::Vulkan)
endif()
# Bridge only consumers of SDL's 2D API, never SDL itself or image/font decoders.
add_library(teeming_renderer_bridge INTERFACE)
target_link_libraries(teeming_renderer_bridge INTERFACE teeming_renderer)
if(MSVC)
    target_compile_options(teeming_renderer_bridge INTERFACE "/FI${CMAKE_CURRENT_SOURCE_DIR}/src/renderer/sdl_bridge.hpp")
else()
    target_compile_options(teeming_renderer_bridge INTERFACE "-include" "${CMAKE_CURRENT_SOURCE_DIR}/src/renderer/sdl_bridge.hpp")
endif()
foreach(consumer gubsy_engine gview_sdl3 teeming teeming_render_scene)
    target_link_libraries(${consumer} PUBLIC teeming_renderer_bridge)
    if(EMSCRIPTEN)
        set_property(TARGET ${consumer} APPEND PROPERTY LINK_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/renderer/webgpu_runtime.js")
    endif()
endforeach()
if(NOT EMSCRIPTEN)
    add_executable(teeming_renderer_tests tests/renderer_test.cpp)
    target_link_libraries(teeming_renderer_tests PRIVATE teeming_renderer)
    add_test(NAME renderer COMMAND teeming_renderer_tests)
    set_tests_properties(renderer PROPERTIES ENVIRONMENT "SDL_VIDEODRIVER=dummy;SDL_AUDIODRIVER=dummy")
endif()
